image: docker:18.06

variables:
  DOCKER_DRIVER: overlay

services:
- docker:18.06-dind

before_script:
- docker info > /dev/null
- apk --update add make git sed bash curl

build:
  tags:
  - docker
  script:
  - ./build.sh
  artifacts:
    paths:
    - build/dist/
    expire_in: 4 weeks
